spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spb?serverTimezone=Asia/Shanghai
    username: root
    password: 20010514
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  application:
#    name: shiro

upload:
  dir:
    avatar: src/main/resources/static/images/avatar

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印

server:
  port: 8080



