spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.121.129.207:3307/spb?serverTimezone=Asia/Shanghai
    username: root
    password: Gzzs0414
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
    password: ''
    port: 6379
    timeout: 1000
#  application:
#    name: shiro

upload:
  dir:
    avatar: src/main/resources/static/images/avatar

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印

server:
  port: 8080



